import FacebookSocialButton from "./buttons/FacebookSocialButton";
import AmazonSocialButton from "./buttons/AmazonSocialButton";
import LinkedInSocialButton from "./buttons/LinkedInSocialButton";
import GoogleSocialButton from "./buttons/GoogleSocialButton";
import MicrosoftSocialButton from "./buttons/MicrosoftSocialButton";
import GitHubSocialButton from "./buttons/GitHubSocialButton";
import TwitterSocialButton from "./buttons/TwitterSocialButton";
import InstagramSocialButton from "./buttons/InstagramSocialButton";
import AppleSocialButton from "./buttons/AppleSocialButton";

export { FacebookSocialButton };
export { AmazonSocialButton };
export { LinkedInSocialButton };
export { GoogleSocialButton };
export { MicrosoftSocialButton };
export { GitHubSocialButton };
export { TwitterSocialButton };
export { InstagramSocialButton };
export { AppleSocialButton };
